/**
 * build-comuni.ts
 *
 * Documentation script: describes how public/data/comuni.json was generated.
 *
 * DATA SOURCES
 * ------------
 * The dataset was extracted using the npm package:
 *   @marketto/belfiore-connector-embedded (v1.2.1)
 *
 * Which in turn embeds official Italian government data from:
 *   - Ministero dell'Interno / ANPR (Anagrafe Nazionale della Popolazione Residente)
 *     URL: https://developers.italia.it/en/anpr
 *     License: CC BY 4.0
 *     Terms: https://github.com/italia/anpr/blob/master/src/archivi/ANPR_archivio_comuni_legenda.md
 *   - Istituto Nazionale di Statistica (ISTAT)
 *     URL: https://www.istat.it
 *     License: CC BY 3.0 IT
 *   - Agenzia delle Entrate
 *
 * FORMAT
 * ------
 * Output: public/data/comuni.json
 * Schema: Array<{ nome: string; provincia: string; codiceCatastale: string }>
 *
 *   - nome: Italian name of the municipality or foreign state
 *   - provincia: Two-letter province code (e.g. "RM", "MI"); "EE" for foreign states
 *   - codiceCatastale: Belfiore code (e.g. "H501" for Roma, "Z110" for Francia)
 *     - Italian municipalities: codes A001–Y999
 *     - Foreign states: codes Z100–Z999
 *
 * GENERATION STEPS
 * ----------------
 * 1. Install the data package:
 *      npm install --save-dev @marketto/belfiore-connector-embedded
 *
 * 2. Run the extraction script (Node.js CJS):
 *
 *    const belfiore = require('@marketto/belfiore-connector-embedded');
 *    const fs = require('fs');
 *    const connector = belfiore.default || belfiore;
 *
 *    async function main() {
 *      const arr = await connector.toArray();
 *
 *      // Filter only currently active places
 *      const now = new Date();
 *      const active = arr.filter(p => {
 *        if (!p.expirationDate) return true;
 *        return new Date(p.expirationDate) > now;
 *      });
 *
 *      // Map to required format
 *      const mapped = active.map(p => ({
 *        nome: p.name,
 *        provincia: p.belfioreCode.startsWith('Z') ? 'EE' : p.province,
 *        codiceCatastale: p.belfioreCode
 *      })).filter(p => p.nome && p.codiceCatastale && p.provincia);
 *
 *      // Sort: Italian municipalities first (alphabetical), then foreign states
 *      mapped.sort((a, b) => {
 *        const aIsForeign = a.codiceCatastale.startsWith('Z');
 *        const bIsForeign = b.codiceCatastale.startsWith('Z');
 *        if (aIsForeign && !bIsForeign) return 1;
 *        if (!aIsForeign && bIsForeign) return -1;
 *        return a.nome.localeCompare(b.nome, 'it');
 *      });
 *
 *      fs.writeFileSync('./public/data/comuni.json', JSON.stringify(mapped));
 *      console.log('Written', mapped.length, 'records');
 *    }
 *    main();
 *
 * STATISTICS (as of 2026-03-02)
 * -----------------------------
 * - Total records: 8112
 *   - Italian municipalities: 7896
 *   - Foreign states: 216
 * - File size: ~527 KB (uncompressed JSON)
 *
 * KEY TEST CASES
 * --------------
 * - Roma     -> provincia: "RM", codiceCatastale: "H501"
 * - Milano   -> provincia: "MI", codiceCatastale: "F205"
 * - Francia  -> provincia: "EE", codiceCatastale: "Z110"
 *
 * USAGE IN APPLICATION
 * --------------------
 * The file is served as a static asset by Astro/Vercel and fetched client-side:
 *
 *   const response = await fetch('/data/comuni.json');
 *   const comuni: Array<{ nome: string; provincia: string; codiceCatastale: string }>
 *     = await response.json();
 */

// This file is documentation only.
// The actual comuni.json was generated by running the steps above.
// To regenerate, reinstall @marketto/belfiore-connector-embedded and
// follow the GENERATION STEPS section above.
